# -*- coding: utf-8 -*-
"""TF Pemilu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sBbmVnvVmN4iMk-JaCX1k60HQKg9gPdA
"""

import re
import numpy as np
import pandas as pd
# import community
# import community.community_louvain
import pandas as pd
# import networkx as nx
import ast
import os
import snscrape.modules.twitter as sntwitter

"""# 2019"""

# Setting variables to be used below
maxTweets = 5000000

# Creating list to append tweet data to
tweets_list = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"pemilu ditunda" since:2019-03-04 until:2022-04-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list.append(tweet)

df = pd.DataFrame(tweets_list)
df.head(10)

df.shape

# Setting variables to be used below
maxTweets = 500000

# Creating list to append tweet data to
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"jokowi 3 periode" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append(tweet)

df1 = pd.DataFrame(tweets_list1)
df1.head(10)

df1.shape

# Setting variables to be used below
maxTweets = 500000

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"masa jabatan presiden" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list2.append(tweet)

df2 = pd.DataFrame(tweets_list2)
df2.head(10)

df2.shape

# Setting variables to be used below
maxTweets = 500000

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"presiden 3 periode" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list2.append(tweet)

df3 = pd.DataFrame(tweets_list2)
df3.head(10)

df3.shape

df = df.append(df1)

df.shape

df = df.append(df2)

df.shape

df.append(df3)

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d %H:%M:%S')
df

df.sort_values(by=['date'],ascending=False)

df.shape

df = df.drop_duplicates(subset=['id'])

df.to_csv('pemiluditunda2019.csv')



"""# 2021"""

# Setting variables to be used below
maxTweets = 50000

# Creating list to append tweet data to
tweets_list = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"3 periode" since:2021-03-15 until:2021-07-15 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list.append(tweet)

df = pd.DataFrame(tweets_list)

df.head(10)

df.shape

# Setting variables to be used below
maxTweets = 50000

# Creating list to append tweet data to
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"masa jabatan presiden" since:2021-03-15 until:2021-07-15 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append(tweet)

df1 = pd.DataFrame(tweets_list1)

df1.head(10)

df1.shape

df1.shape

df.shape

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d %H:%M:%S')
df

df1['date'] = pd.to_datetime(df1['date'], format='%Y-%m-%d %H:%M:%S')
df1

df = df.append(df1)

df.sort_values(by=['date'],ascending=False)

# Setting variables to be used below
maxTweets = 50000

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"presiden diperpanjang" since:2021-03-15 until:2020-07-15 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list2.append(tweet)

df2 = pd.DataFrame(tweets_list2)
df2.shape

for tweets2, value2 in df2.iterrows():
    for tweets, value in df.iterrows():
        if value2['id'] == value['id']:
            df2.drop(tweets2, inplace=True)
df2.shape

df2['date'] = pd.to_datetime(df2['date'], format='%Y-%m-%d %H:%M:%S')
df2 #ini harus dilakuin dulu sebelum dibandingin

df = df.append(df2)

df.sort_values(by=['date'],ascending=False)

df = df.drop_duplicates(subset=['id'])

df.to_csv('pemilu2021coba.csv')

"""# 2022"""

# Setting variables to be used below
maxTweets = 500000

# Creating list to append tweet data to
tweets_list = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"pemilu ditunda" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list.append(tweet)

df = pd.DataFrame(tweets_list)
df.head(10)

df.shape

# Setting variables to be used below
maxTweets = 500000

# Creating list to append tweet data to
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"jokowi 3 periode" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append(tweet)

df1 = pd.DataFrame(tweets_list1)
df1.head(10)

df1.shape

# Setting variables to be used below
maxTweets = 50000

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"masa jabatan presiden" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list2.append(tweet)

df2 = pd.DataFrame(tweets_list2)
df2.head(10)

df2.shape

# Setting variables to be used below
maxTweets = 50000

# Creating list to append tweet data to
tweets_list3 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"presiden 3 periode" since:2022-03-04 until:2022-07-04 lang:id').get_items()):
    if i>maxTweets:
        break
    tweets_list3.append(tweet)

df3 = pd.DataFrame(tweets_list3)
df3.head(10)

df3.shape

df = df.append(df1)

df.shape

df = df.append(df2)

df.shape

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d %H:%M:%S')
df

df.sort_values(by=['date'],ascending=False)

df.drop_duplicates(subset=['id'])

df.to_csv('tfpemilu22coba.csv')

"""# Combine All"""

df2019 = pd.read_csv('pemiluditunda2019.csv')
df2021 = pd.read_csv('pemilu2021coba.csv')
df2022 = pd.read_csv('pemilu2022coba.csv')

df = df2019.append(df2021)
df = df.append(df2022)

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d %H:%M:%S')
df

df.sort_values(by=['date'],ascending=False)

df.drop_duplicates(subset=['id'])

df.to_csv('tfpemiluall.csv')